#!/usr/bin/env python3
"""
MechaGen Phase 3 — CadQuery Worker
===================================
Receives a JSON job from stdin, builds a CadQuery solid, exports STL.
Returns a JSON result to stdout. Exit 0 = success, 1 = build error.

Contract (stdin):
{
  "jobId":      string,
  "source":     string,   -- Python source generated by cadqueryTranslator.js
  "outputPath": string,   -- absolute path to write the .stl file
  "timeout":    int        -- seconds (worker enforces its own operations timeout)
}

Contract (stdout):
{
  "jobId":         string,
  "success":       bool,
  "stlPath":       string | null,
  "stlSizeBytes":  int | null,
  "executionMs":   int,
  "stdout":        string,
  "stderr":        string,
  "error":         string | null,
  "meshCheck":     { "triangleCount": int, "valid": bool } | null
}
"""

import sys
import json
import os
import time
import io
import traceback

_stdout_capture = io.StringIO()
_stderr_capture = io.StringIO()


def run_build(source_code: str, output_path: str) -> dict:
    """
    Execute the CadQuery source in a restricted namespace and export STL.
    Returns {"result": cq_result, "error": None} or {"result": None, "error": str}
    """
    import cadquery as cq

    namespace = {
        "cq": cq,
        "__builtins__": {
            # Minimal builtins — only math-safe operations
            "abs": abs,
            "round": round,
            "min": min,
            "max": max,
            "range": range,
            "len": len,
            "list": list,
            "tuple": tuple,
            "dict": dict,
            "str": str,
            "int": int,
            "float": float,
            "bool": bool,
            "True": True,
            "False": False,
            "None": None,
            "print": print,
            "enumerate": enumerate,
            "zip": zip,
        }
    }

    try:
        exec(compile(source_code, "<cadquery_source>", "exec"), namespace)
    except Exception as e:
        return {"result": None, "error": f"Execution error: {e}\n{traceback.format_exc()}"}

    # The source must assign the final solid to `result`
    result = namespace.get("result", None)
    if result is None:
        return {"result": None, "error": "Source did not assign `result` variable"}

    # Export STL
    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        cq.exporters.export(result, output_path)
    except Exception as e:
        return {"result": None, "error": f"STL export error: {e}\n{traceback.format_exc()}"}

    return {"result": result, "error": None}


def check_mesh(stl_path: str) -> dict:
    """
    Basic STL sanity check — count triangles, validate non-empty.
    Tries trimesh first, falls back to manual count.
    """
    try:
        import trimesh
        mesh = trimesh.load(stl_path, force='mesh')
        return {
            "triangleCount": int(len(mesh.faces)),
            "valid": mesh.is_valid and len(mesh.faces) > 0,
        }
    except ImportError:
        pass

    # Manual fallback: ASCII/binary STL triangle count
    try:
        with open(stl_path, 'rb') as f:
            data = f.read()
        if data[:5] == b'solid':
            # ASCII STL
            count = data.decode('utf-8', errors='replace').count('facet normal')
        else:
            # Binary STL: 80-byte header + 4-byte uint32 triangle count
            if len(data) >= 84:
                count = int.from_bytes(data[80:84], 'little')
            else:
                count = 0
        return {"triangleCount": count, "valid": count > 0}
    except Exception:
        return {"triangleCount": 0, "valid": False}


def main():
    t_start = time.monotonic()

    try:
        raw_input = sys.stdin.read()
        job = json.loads(raw_input)
    except Exception as e:
        result = {
            "jobId": None, "success": False, "stlPath": None,
            "stlSizeBytes": None, "executionMs": 0,
            "stdout": "", "stderr": "",
            "error": f"Invalid job payload: {e}",
            "meshCheck": None,
        }
        print(json.dumps(result))
        sys.exit(1)

    job_id     = job.get("jobId", "unknown")
    source     = job.get("source", "")
    output_path = job.get("outputPath", "")

    if not source.strip():
        result = {
            "jobId": job_id, "success": False, "stlPath": None,
            "stlSizeBytes": None, "executionMs": 0,
            "stdout": "", "stderr": "",
            "error": "No CadQuery source provided",
            "meshCheck": None,
        }
        print(json.dumps(result))
        sys.exit(1)

    if not output_path:
        result = {
            "jobId": job_id, "success": False, "stlPath": None,
            "stlSizeBytes": None, "executionMs": 0,
            "stdout": "", "stderr": "",
            "error": "No outputPath provided",
            "meshCheck": None,
        }
        print(json.dumps(result))
        sys.exit(1)

    # Redirect stdout/stderr during build
    import sys as _sys
    old_stdout, old_stderr = _sys.stdout, _sys.stderr
    _sys.stdout = _stdout_capture
    _sys.stderr = _stderr_capture

    build_result = None
    try:
        build_result = run_build(source, output_path)
    finally:
        _sys.stdout = old_stdout
        _sys.stderr = old_stderr

    exec_ms = int((time.monotonic() - t_start) * 1000)
    captured_out = _stdout_capture.getvalue()
    captured_err = _stderr_capture.getvalue()

    if build_result is None or build_result.get("error"):
        result = {
            "jobId": job_id, "success": False, "stlPath": None,
            "stlSizeBytes": None, "executionMs": exec_ms,
            "stdout": captured_out, "stderr": captured_err,
            "error": build_result["error"] if build_result else "Unknown build error",
            "meshCheck": None,
        }
        print(json.dumps(result))
        sys.exit(1)

    # Verify STL file
    stl_size = 0
    mesh_check = None
    try:
        stl_size = os.path.getsize(output_path)
        mesh_check = check_mesh(output_path)
    except Exception as e:
        result = {
            "jobId": job_id, "success": False, "stlPath": output_path,
            "stlSizeBytes": 0, "executionMs": exec_ms,
            "stdout": captured_out, "stderr": captured_err,
            "error": f"STL post-check failed: {e}",
            "meshCheck": None,
        }
        print(json.dumps(result))
        sys.exit(1)

    if stl_size == 0 or (mesh_check and not mesh_check["valid"]):
        result = {
            "jobId": job_id, "success": False, "stlPath": output_path,
            "stlSizeBytes": stl_size, "executionMs": exec_ms,
            "stdout": captured_out, "stderr": captured_err,
            "error": "STL file is empty or contains no valid triangles",
            "meshCheck": mesh_check,
        }
        print(json.dumps(result))
        sys.exit(1)

    result = {
        "jobId":        job_id,
        "success":      True,
        "stlPath":      output_path,
        "stlSizeBytes": stl_size,
        "executionMs":  exec_ms,
        "stdout":       captured_out,
        "stderr":       captured_err,
        "error":        None,
        "meshCheck":    mesh_check,
    }
    print(json.dumps(result))
    sys.exit(0)


if __name__ == "__main__":
    main()
